# Generated by Django 3.0.3 on 2021-07-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='California',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=200, null=True)),
                ('agency_collection_num', models.IntegerField(default=0)),
                ('collection_id', models.IntegerField(default=0)),
                ('site_name', models.CharField(max_length=200, null=True)),
                ('identified_by', models.CharField(max_length=200, null=True)),
                ('trap_type', models.CharField(max_length=200, null=True)),
                ('lure', models.CharField(max_length=200, null=True)),
                ('num_trap', models.IntegerField(default=0)),
                ('trap_nights', models.IntegerField(default=0)),
                ('trap_problem', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('females_unfed', models.IntegerField(null=True)),
                ('males', models.IntegerField(null=True)),
                ('females_gravid', models.IntegerField(null=True)),
                ('females_bloodfed', models.IntegerField(null=True)),
                ('females_mixed', models.IntegerField(null=True)),
                ('larvae', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_raw', models.CharField(max_length=12000, null=True)),
                ('genome_ORF', models.CharField(max_length=12000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('Country', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('County', models.CharField(max_length=50, null=True)),
                ('Subcounty', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('District', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.Location')),
            ],
        ),
        migrations.CreateModel(
            name='MosSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosSpec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sequenced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenced', models.CharField(default='No', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TrapID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapID', models.CharField(max_length=105, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicGenomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=25, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('start_ORF', models.IntegerField(default=0)),
                ('end_ORF', models.IntegerField(default=0)),
                ('collection_date', models.DateField(null=True)),
                ('genotype', models.IntegerField(null=True)),
                ('genome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MosDB.Genome')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MosDB.MosSpecies')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MosDB.Location')),
                ('virus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MosDB.Virus')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleID', models.CharField(max_length=10)),
                ('accession', models.CharField(max_length=10)),
                ('positive', models.IntegerField(default=0)),
                ('pool_num', models.IntegerField(default=0)),
                ('num_female_mos', models.IntegerField(default=0)),
                ('genome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MosDB.Genome')),
                ('metaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MetaData')),
                ('mos_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MosSpecies')),
                ('sequenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.Sequenced')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.Virus')),
            ],
        ),
        migrations.CreateModel(
            name='MosCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('males', models.IntegerField(default=0)),
                ('females', models.IntegerField(default=0)),
                ('metaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MetaData')),
                ('mospec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MosSpecies')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='trap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.TrapID'),
        ),
        migrations.CreateModel(
            name='California_Positives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk', models.IntegerField()),
                ('trap_style', models.CharField(max_length=200)),
                ('california', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.California')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.Pool')),
            ],
        ),
        migrations.AddField(
            model_name='california',
            name='meta_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MetaData'),
        ),
        migrations.AddField(
            model_name='california',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MosDB.MosSpecies'),
        ),
    ]
