# Generated by Django 3.0.3 on 2021-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='California',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=200, null=True)),
                ('agency_collection_num', models.IntegerField(default=0)),
                ('collection_id', models.IntegerField(default=0)),
                ('site_name', models.CharField(max_length=200, null=True)),
                ('identified_by', models.CharField(max_length=200, null=True)),
                ('trap_type', models.CharField(max_length=200, null=True)),
                ('lure', models.CharField(max_length=200, null=True)),
                ('num_trap', models.IntegerField(default=0)),
                ('trap_nights', models.IntegerField(default=0)),
                ('trap_problem', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('females_unfed', models.IntegerField(null=True)),
                ('males', models.IntegerField(null=True)),
                ('females_gravid', models.IntegerField(null=True)),
                ('females_bloodfed', models.IntegerField(null=True)),
                ('females_mixed', models.IntegerField(null=True)),
                ('larvae', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'MosDB_california',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='California_Positives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk', models.IntegerField()),
                ('trap_style', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'MosDB_positives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_raw', models.CharField(max_length=12000, null=True)),
                ('genome_ORF', models.CharField(max_length=12000, null=True)),
            ],
            options={
                'db_table': 'MosDB_genome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('Country', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('County', models.CharField(max_length=50, null=True)),
                ('Subcounty', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('District', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'MosDB_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateField()),
            ],
            options={
                'db_table': 'MosDB_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MosCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('males', models.IntegerField(default=0)),
                ('females', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MosDB_moscount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MosSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosSpec', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MosDB_mosspecies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleID', models.CharField(max_length=10)),
                ('accession', models.CharField(max_length=10)),
                ('positive', models.IntegerField(default=0)),
                ('pool_num', models.IntegerField(default=0)),
                ('num_female_mos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MosDB_virus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicGenomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=25, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('start_ORF', models.IntegerField(default=0)),
                ('end_ORF', models.IntegerField(default=0)),
                ('collection_date', models.DateField(null=True)),
                ('genotype', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'MosDB_publicgenomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequenced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenced', models.CharField(default='No', max_length=25)),
            ],
            options={
                'db_table': 'MosDB_sequenced',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrapID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapID', models.CharField(max_length=105, unique=True)),
            ],
            options={
                'db_table': 'MosDB_trapid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
