# Generated by Django 3.0.3 on 2021-06-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'WeatherDB_counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'WeatherDB_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'WeatherDB_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Latitudelongitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'WeatherDB_latitudelongitude',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensortype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'WeatherDB_sensortype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weatherresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_amount', models.FloatField(blank=True, null=True)),
                ('max_temp', models.IntegerField(blank=True, null=True)),
                ('mean_temp', models.IntegerField(blank=True, null=True)),
                ('min_temp', models.IntegerField(blank=True, null=True)),
                ('max_dewpnt', models.IntegerField(blank=True, null=True)),
                ('mean_dewpnt', models.IntegerField(blank=True, null=True)),
                ('min_dewpnt', models.IntegerField(blank=True, null=True)),
                ('max_humid', models.IntegerField(blank=True, null=True)),
                ('min_humid', models.IntegerField(blank=True, null=True)),
                ('max_wind', models.FloatField(blank=True, null=True)),
                ('max_bar', models.IntegerField(blank=True, null=True)),
                ('min_bar', models.IntegerField(blank=True, null=True)),
                ('max_sol_rad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WeatherDB_weatherresults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weathersensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'WeatherDB_weathersensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weatherstations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_id', models.IntegerField(unique=True)),
                ('old_station_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('elevation', models.IntegerField()),
                ('station_loc_description', models.TextField(blank=True, null=True)),
                ('new_rain_id', models.IntegerField(blank=True, null=True)),
                ('old_rain_id', models.IntegerField(blank=True, null=True)),
                ('new_water_level_id', models.IntegerField(blank=True, null=True)),
                ('old_water_level_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WeatherDB_weatherstations',
                'managed': False,
            },
        ),
    ]
